// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auto-height-textarea-root': string;
  'bbs-cus-bootstrap-ui': string;
  'bbs-cus-error': string;
  'bbs-cus-fieldset-container': string;
  'bbs-cus-fieldset-focus': string;
  'bbs-cus-fieldset-legend': string;
  'bbs-cus-fieldset-valid-form': string;
  'bbs-cus-filedset-wrapper': string;
  'bbs-cus-label-text': string;
  'bbs-cus-material-ui': string;
  'bbs-cus-success': string;
  'bbs-cus-text-error': string;
  'bbs-cus-text-success': string;
  'bbs-cus-valid-field': string;
  'error-msg': string;
}
export const cssExports: CssExports
export default cssExports
