// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bbs-btn': string;
  'bbs-btn-loading': string;
  'bbs-btn-text': string;
  'bbs-disabled': string;
  'error-color': string;
  'info-color': string;
  'no-gap': string;
  'secondary-color': string;
  'success-color': string;
  'warning-color': string;
}
export const cssExports: CssExports;
export default cssExports;
