// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bbs-at': string;
  'bbs-msg-action': string;
  'bbs-msg-action-edit': string;
  'bbs-msg-action-no-edit': string;
  'bbs-msg-body': string;
  'bbs-msg-wrapper': string;
  'bbs-reply-btn': string;
  'bbs-reply-wrapper': string;
  'msg-small': string;
}
export const cssExports: CssExports;
export default cssExports;
