// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bbs-avatar': string;
  'bbs-msg-date': string;
  'bbs-msg-head-info': string;
  'bbs-msg-header': string;
  'bbs-nickname': string;
  'header-sm': string;
}
export const cssExports: CssExports
export default cssExports
