// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar-panel-box': string;
  'avatar-panel-item': string;
  'bbs-avatar': string;
}
export const cssExports: CssExports;
export default cssExports;
